import type { MouseEvent } from "react";
import ButtonLink from "../ui/ButtonLink";
import HeroArtwork from "./HeroArtwork";
import Reveal from "./Reveal";
import { CAPABILITIES, ROUTES } from "../../utils/constants";

export default function Hero() {
	const handleScrollToProblem = (event: MouseEvent<HTMLAnchorElement>) => {
		event.preventDefault();
		document.getElementById("problem")?.scrollIntoView({ behavior: "smooth" });
	};
	return <section id="hero" data-cinematic-hero className="hero-vault relative isolate flex min-h-[100svh] flex-col justify-center overflow-hidden pb-20 pt-32 sm:pt-40 lg:pb-28 lg:pt-44"><div aria-hidden="true" className="hero-vault__measurements"><span className="hero-vault__corner hero-vault__corner--tl" /><span className="hero-vault__corner hero-vault__corner--tr" /><span className="hero-vault__corner hero-vault__corner--bl" /><span className="hero-vault__corner hero-vault__corner--br" /><div className="hero-vault__axis hero-vault__axis--x" /><div className="hero-vault__axis hero-vault__axis--y" /></div><HeroArtwork /><div className="site-container relative z-10 w-full"><div className="max-w-3xl"><Reveal><div className="hero-kicker"><span className="hero-kicker__pulse" />ARTIFACT PROTECTION SYSTEM / 001</div><p className="mt-3 label-tech">Digital art protection infrastructure</p></Reveal><Reveal delay={120}><h1 className="hero-statement mt-8 font-display font-bold leading-[0.82] tracking-tightest text-white"><span>PROTECT</span><span className="hero-statement__ghost">THE ART.</span><span className="hero-statement__prove">PROVE</span><span>THE ORIGINAL.</span></h1></Reveal><Reveal delay={240}><p className="mt-9 max-w-md text-base font-normal leading-relaxed text-silver-300 sm:text-lg">A containment system for authorship: latent watermarking, deliberate AI resistance, and cryptographic evidence for the work that matters.</p></Reveal><Reveal delay={360}><div className="mt-10 flex flex-col gap-4 sm:flex-row sm:items-center"><ButtonLink to={ROUTES.protect} size="md">Protect your artwork</ButtonLink><a href="#problem" onClick={handleScrollToProblem} className="hero-secondary-action group"><span>Enter the system</span><svg className="h-3.5 w-3.5 transition-transform duration-300 group-hover:translate-y-0.5" viewBox="0 0 16 16" fill="none"><path d="M8 3V13M8 13L3.5 8.5M8 13L12.5 8.5" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg></a></div></Reveal></div><Reveal delay={500} className="relative mt-16 hidden md:block lg:mt-24"><div className="hero-readout"><span>CONTAINMENT / NOMINAL</span><ul><li>X 41.203</li><li>Y 08.924</li><li>Z 000.1</li><li>FRAME 001</li></ul></div><div className="mt-5 flex flex-wrap items-center justify-between gap-6 border-t border-white/10 pt-5"><span className="font-mono text-[10px] uppercase tracking-widest text-silver-500">SYSTEM CAPABILITIES</span><ul className="flex flex-wrap items-center gap-x-7 gap-y-3">{CAPABILITIES.map((item) => <li key={item} className="flex items-center gap-2 font-mono text-[10px] tracking-wider text-silver-300"><span className="h-1 w-1 rounded-full bg-ice-400/80" /><span>{item}</span></li>)}</ul></div></Reveal></div></section>;
}
