import { useRef, useState } from "react";
import ArtworkCanvas from "../artwork/ArtworkCanvas";
import FingerprintMark from "./FingerprintMark";
import Reveal from "./Reveal";
import SectionHeading from "../ui/SectionHeading";
import { useScrollProgress } from "../../hooks/useScrollProgress";
import { PROTECTION_STAGES } from "../../utils/constants";

const HASH_FRAGMENT = "a8f1 09c4 7e2b … 5c9e";
const PROVENANCE_NODES = ["Certificate", "Ownership", "Rights"];

function StageArtwork({ active, id }: { active: number; id: string }) {
	const on = (index: number) => active >= index;
	const state = (index: number) => on(index) ? "opacity-100 translate-y-0 scale-100" : "pointer-events-none translate-y-4 scale-95 opacity-0";
	return <div className="relative mx-auto aspect-[3/4] w-full max-w-[280px] sm:max-w-[320px] lg:max-w-[360px]" aria-hidden="true"><div className={`absolute -inset-6 rounded-[28px] border transition-all duration-1000 ease-premium ${on(4) ? "border-ice-400/50 shadow-[0_0_50px_rgba(56,189,248,0.25),inset_0_0_20px_rgba(56,189,248,0.1)]" : "border-white/[0.08]"}`} /><ArtworkCanvas id={id} className="relative h-full w-full rounded-2xl border border-white/10 shadow-2xl" /><div className={`absolute inset-0 rounded-2xl mix-blend-screen transition-all duration-700 ease-premium [background-image:radial-gradient(rgba(56,189,248,0.6)_0.7px,transparent_0.8px)] [background-size:16px_16px] ${state(1)}`} /><div className={`glass-plane -right-6 top-8 h-[70%] w-[68%] rotate-[4deg] transition-all duration-700 ease-premium ${state(2)}`}><p className="absolute bottom-4 left-5 font-mono text-[10px] uppercase tracking-wider text-ice-300">Perturbation · Deterministic</p></div><div className={`absolute -left-6 -top-6 flex items-center gap-3 rounded-xl border border-white/15 bg-ink-950/90 p-2.5 shadow-xl backdrop-blur-md transition-all duration-700 ease-premium ${state(0)}`}><FingerprintMark className="h-9 w-9 text-ice-400" /><div><p className="font-mono text-[9px] uppercase tracking-widest text-silver-400">SHA-256 SEAL</p><p className="font-mono text-[10px] text-silver-200">{HASH_FRAGMENT}</p></div></div><div className={`absolute -right-20 bottom-10 hidden flex-col gap-4 rounded-xl border border-white/10 bg-ink-950/80 p-3 backdrop-blur-md transition-all duration-700 ease-premium sm:flex ${state(3)}`}><span className="font-mono text-[9px] uppercase tracking-wider text-ice-400">LEDGER STATE</span>{PROVENANCE_NODES.map((node, index) => <div key={node} className="flex items-center gap-2.5"><span className="relative flex h-5 w-5 items-center justify-center"><span className="absolute inset-0 rounded-full border border-ice-400/40" /><span className="h-1.5 w-1.5 rounded-full bg-ice-300" />{index < PROVENANCE_NODES.length - 1 && <span className="absolute left-1/2 top-full h-4 w-px -translate-x-1/2 bg-white/20" />}</span><span className="font-mono text-[10px] text-silver-200">{node}</span></div>)}</div><div className={`absolute -bottom-8 left-1/2 flex -translate-x-1/2 items-center gap-2.5 rounded-full border border-emerald-400/40 bg-ink-950/90 px-4 py-2 shadow-xl backdrop-blur-md transition-all duration-700 ease-premium ${state(4)}`}><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" /><span className="font-mono text-[10px] font-semibold uppercase tracking-wider text-emerald-300">INTEGRITY AUDIT PASSED</span></div></div>;
}

function StageList({ active, onSelect }: { active: number; onSelect?: (idx: number) => void }) {
	return <ol className="flex flex-col gap-2">{PROTECTION_STAGES.map((stage, index) => { const isActive = index === active; const isPast = index < active; return <li key={stage.id} onClick={() => onSelect?.(index)} className={`group cursor-pointer rounded-xl border p-5 transition-all duration-300 ${isActive ? "border-ice-400/40 bg-white/[0.04] shadow-[0_0_30px_rgba(56,189,248,0.1)]" : isPast ? "border-white/10 bg-white/[0.015] opacity-75 hover:border-white/20 hover:opacity-100" : "border-transparent bg-transparent opacity-40 hover:opacity-75"}`}><div className="flex items-start gap-4"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg font-mono text-xs font-bold ${isActive ? "border border-ice-400/40 bg-ice-400/20 text-ice-300" : "bg-white/5 text-silver-400"}`}>{stage.index}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-4"><h3 className={`font-display text-lg font-semibold tracking-wide ${isActive ? "text-silver-50" : "text-silver-300"}`}>{stage.name}</h3><span className="font-mono text-[10px] uppercase tracking-wider text-ice-400">{stage.technical}</span></div><div className={`grid transition-all duration-500 ease-premium ${isActive ? "mt-2 grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`}><p className="min-h-0 overflow-hidden text-xs leading-relaxed text-silver-400">{stage.description}</p></div></div></div></li>; })}</ol>;
}

export default function ProtectionLayers() {
	const trackRef = useRef<HTMLDivElement>(null); const progress = useScrollProgress(trackRef); const count = PROTECTION_STAGES.length; const [manualStage, setManualStage] = useState<number | null>(null); const scrollActive = Math.min(count - 1, Math.floor(progress * count)); const active = manualStage ?? scrollActive;
	return <section id="technology" className="relative scroll-mt-24 py-28 sm:py-36 lg:py-40"><div className="site-container"><Reveal><SectionHeading eyebrow="MULTI-TIER SECURITY ARCHITECTURE" title={<>Five Defense Layers.<br />One Mathematical Artifact.</>} body="The masterwork remains at the core while each cryptographic layer adds verifiable evidence around it, spanning deterministic perturbations to on-chain provenance." /></Reveal></div><div ref={trackRef} className="relative mt-16 hidden lg:block" style={{ minHeight: `${count * 75 + 40}vh` }}><div className="sticky top-20 flex min-h-[80vh] items-center"><div className="site-container grid grid-cols-[0.9fr_1.1fr] items-center gap-20"><StageArtwork active={active} id="layers-desktop" /><div><StageList active={active} onSelect={setManualStage} /><div className="mt-8 h-1 w-full overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full bg-gradient-to-r from-ice-400 to-blue-600 transition-all duration-500 ease-premium" style={{ width: `${((active + 1) / count) * 100}%` }} /></div></div></div></div></div><div className="site-container mt-16 lg:hidden"><Reveal><StageArtwork active={active} id="layers-mobile" /></Reveal><div className="mt-16"><StageList active={active} onSelect={setManualStage} /></div></div></section>;
}
