import Reveal from "./Reveal";
import SectionHeading from "../ui/SectionHeading";

const PIPELINE = [
	{ id: "01", name: "Identity", tech: "SHA-256 artwork fingerprint" }, { id: "02", name: "Watermark", tech: "LSB steganographic watermark" }, { id: "03", name: "AI Shield", tech: "AI Shield · Deterministic frequency perturbation" }, { id: "04", name: "Integrity", tech: "Cryptographic parity and hash verification" }, { id: "05", name: "Provenance", tech: "Registry-backed artifact record" }, { id: "06", name: "Rights", tech: "Usage-rights declaration · enforcement in development" },
];
const OUTPUTS = [
	{ title: "Protected Digital Artifact", tag: "OUTPUT 01", desc: "A PNG artifact with an embedded LSB watermark and deterministic AI Shield frequency perturbation designed to disrupt unauthorized model training." }, { title: "SHA-256 Seal", tag: "OUTPUT 02", desc: "A digest of the protected file, source fingerprint, and embedded watermark reference for deterministic integrity checks." }, { title: "Verification Reference", tag: "OUTPUT 03", desc: "A reference saved in this browser to verify the protected artifact against its registered fingerprint and watermark." },
];

export default function ShieldIntro() {
	return <section id="protection" className="relative scroll-mt-24 overflow-hidden py-28 sm:py-36 lg:py-44"><div aria-hidden="true" className="pointer-events-none absolute inset-x-0 top-0 h-px bg-hairline-x" /><div className="site-container"><Reveal><SectionHeading align="center" eyebrow="BETA PROTECTION PIPELINE" title={<>One Masterwork. One Identity.<br className="hidden sm:block" /> Six Clear Protection Layers.</>} body="ArtShield generates a SHA-256 fingerprint, embeds an LSB watermark and deterministic AI Shield perturbation, then makes integrity checks and a registry record available. Rights enforcement is in development." /></Reveal><Reveal delay={150} className="mt-20 lg:mt-24"><div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 sm:p-8 backdrop-blur-xl"><ol className="flex flex-col gap-6 lg:grid lg:grid-cols-3 lg:gap-x-8 lg:gap-y-7">{PIPELINE.map((step) => <li key={step.name} className="flex min-w-0 items-center gap-4 lg:items-start"><span className="relative flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-white/[0.02] text-silver-400"><span className="font-mono text-xs font-bold">{step.id}</span></span><div className="flex min-w-0 flex-col"><span className="font-display text-sm font-semibold text-silver-100">{step.name}</span><span className="font-mono text-[10px] leading-relaxed text-silver-400">{step.tech}</span></div></li>)}</ol></div></Reveal><div className="mx-auto mt-16 grid max-w-5xl gap-6 sm:grid-cols-3 lg:mt-20">{OUTPUTS.map((output, index) => <Reveal key={output.title} delay={index * 100}><div className="flex h-full flex-col justify-between rounded-xl border border-white/10 bg-white/[0.02] p-6 backdrop-blur-md transition-all duration-300 hover:border-ice-400/30 hover:bg-white/[0.04]"><div><span className="font-mono text-[10px] font-semibold tracking-wider text-ice-400">{output.tag}</span><h3 className="mt-3 font-display text-base font-semibold text-silver-50">{output.title}</h3><p className="mt-2 text-xs leading-relaxed text-silver-400">{output.desc}</p></div></div></Reveal>)}</div></div></section>;
}
